### ISSUE TITLE
Dropdown component is breaking styleguide

### ISSUE THREAD

**Issue by voutilad** [taskanalytics/genus#35]
Once you visit the dropdown component page (http://genus.taskanalytics.com/components/dropdown) you cannot navigate away. Clicks to other links end up triggering the dropdown show/hide.

**Comment by nervetattoo** [comment]
That symptom is truly fascinating in itself. Funny bugs aside, I will look at this tonight. The dropdown component is in the process of a rewrite anyway in the cards branch.
